"""Tailor a resume with Gemini from a job description and optional source resume."""

from __future__ import annotations

import json
import os
import re
import time
from typing import Dict, Optional

_JSON_FENCE = re.compile(r"```(?:json)?\s*(\{.*\})\s*```", re.DOTALL)
# Lite models first: they stay available when the main Flash model returns 503.
_MODELS = (
    "gemini-2.5-flash-lite",
    "gemini-2.0-flash-lite",
    "gemini-2.0-flash",
    "gemini-2.5-flash",
    "gemini-flash-latest",
)


def _overloaded(exc: Exception) -> bool:
    text = str(exc).lower()
    return any(token in text for token in ("503", "429", "unavailable", "high demand", "resource_exhausted"))


def gemini_api_key() -> str:
    key = (os.environ.get("GEMINI_API_KEY") or "").strip()
    if key:
        return key
    secrets_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        ".streamlit",
        "secrets.toml",
    )
    if os.path.isfile(secrets_path):
        text = open(secrets_path, encoding="utf-8").read()
        match = re.search(r'GEMINI_API_KEY\s*=\s*"([^"]+)"', text)
        if match:
            return match.group(1).strip()
    try:
        import streamlit as st

        return str(st.secrets.get("GEMINI_API_KEY", "")).strip()
    except Exception:
        return ""


def _parse_json(raw: str) -> Dict:
    text = (raw or "").strip()
    fenced = _JSON_FENCE.search(text)
    if fenced:
        text = fenced.group(1)
    start = text.find("{")
    end = text.rfind("}")
    if start >= 0 and end > start:
        text = text[start : end + 1]
    data = json.loads(text)
    if not isinstance(data, dict):
        raise ValueError("Gemini did not return a resume object.")
    return data


def _clean(value: object, fallback: str = "") -> str:
    if value is None:
        return fallback
    if isinstance(value, list):
        return "\n".join(str(item).strip() for item in value if str(item).strip())
    return str(value).strip() or fallback


def tailor_resume(
    jd_text: str,
    source_resume: str = "",
    name: str = "",
    contact: str = "",
    target_title: str = "",
) -> Dict[str, str]:
    """Return structured resume fields written for the job description."""
    key = gemini_api_key()
    if not key:
        raise RuntimeError("Gemini API key is missing.")

    from google import genai
    from google.genai import types

    prompt = f"""
You are an expert resume writer. Analyze the job description and write a one-page,
ATS-friendly, professional resume. Return ONLY JSON with these string fields:
name, title, email, phone, location, summary, skills, experience, education, projects, certifications.

Rules:
- Mirror the job's title, keywords, and required tools in the summary and bullets.
- Summary: 3 tight sentences, third person or implied subject, no "I".
- skills: comma-separated. Put the job's must-have skills first.
- experience format, blank line between jobs:
  Job Title | Company | Mon YYYY - Mon YYYY
  - Action verb, what was done, a tool from the job, and a measurable result
  - Second bullet
  Write 2 jobs when the source resume has them, otherwise 1 strong role.
- education format:
  Degree, Field
  Institution | Years
- projects: one project title then bullets that show a required skill.
- certifications: one item per line, or empty string.
- If a current resume is provided, use ONLY employers, dates, degrees, and tools that appear in it. Rewrite wording to fit the job. Do not invent companies.
- If no current resume is provided, still produce a complete professional draft for the target role. Use company name "Previous Employer" so the user can replace it. Do not invent a university name; use "Your University" if unknown.
- Do not mention that the text was generated by AI.

Candidate name: {name or "Your Name"}
Contact line: {contact or ""}
Target title: {target_title or "Infer the best title from the job description"}

JOB DESCRIPTION:
{jd_text[:8000]}

CURRENT RESUME (may be empty):
{source_resume[:8000]}
""".strip()

    client = genai.Client(api_key=key)
    config = types.GenerateContentConfig(
        automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
        temperature=0.4,
    )
    last_error: Optional[Exception] = None
    raw = ""
    for model in _MODELS:
        for attempt in range(3):
            try:
                response = client.models.generate_content(model=model, contents=prompt, config=config)
                raw = getattr(response, "text", "") or ""
                if raw.strip():
                    break
            except Exception as exc:
                last_error = exc
                raw = ""
                if _overloaded(exc) and attempt < 2:
                    time.sleep(1.2 * (attempt + 1))
                    continue
                break
        if raw.strip():
            break
    if not raw.strip():
        raise RuntimeError(
            "Gemini is busy right now. Wait a few seconds and click Build again."
            if last_error and _overloaded(last_error)
            else f"Gemini did not return a resume. {last_error or ''}".strip()
        )

    data = _parse_json(raw)
    email = _clean(data.get("email"), "email@example.com")
    phone = _clean(data.get("phone"), "")
    location = _clean(data.get("location"), "")
    if contact and (not email or email == "email@example.com"):
        email_match = re.search(r"[\w.+-]+@[\w-]+\.[\w.]+", contact)
        if email_match:
            email = email_match.group(0)
    return {
        "name": _clean(data.get("name"), name or "Your Name"),
        "title": _clean(data.get("title"), target_title or "Target Role"),
        "email": email,
        "phone": phone,
        "location": location,
        "summary": _clean(data.get("summary")),
        "skills": _clean(data.get("skills")).replace("\n", ", "),
        "experience": _clean(data.get("experience")),
        "education": _clean(data.get("education")),
        "projects": _clean(data.get("projects")),
        "certifications": _clean(data.get("certifications")),
    }
